9th Jan 2024

1. What is 7 to the power 4

In [8]:
a=7**4
print(a)

2401


2. Split the string:
s="hi there sam!"
into list

In [9]:
s="hi there sam!"
s.split()


['hi', 'there', 'sam!']

3. Given the variables:
planet=earth
diameter=12742
use .format() to print the following string:
The diameter of Earth is 12742 kilometers.

In [10]:
planet='earth'
diameter=12742
print(f'The diameter of {planet} is {diameter} kilometers.')

The diameter of earth is 12742 kilometers.


4. given the nested list,use indexing to grab the word "hello".
lst=[1,2,[3,4],[5,[100,200,["hello"]],23,11],1,7]

In [11]:
lst=[1,2,[3,4],[5,[100,200,["hello"]],23,11],1,7]
lst[3][1][2][0]

'hello'

5. given the nested dictionary grab the word "hello":
d={'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [12]:
d={'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

'hello'

6. What is the main difference between a tuple and a list ?
ans: -Tuples are created using parentheses () and may contain a mix of data   
      types.It is not changable.

     -Lists are created using square brackets [] and can also contain a mix of data types.It is changable.




7. Create a function that grabs the email the email website domain from a string in the form:

user@domain.com
so for example passing "user@domain.com" would return domain.com

In [13]:
def extract_email_domain(email):
    return email.split('@')[-1]


a= input("email :")
domain = extract_email_domain(a)
print("domain :", domain)

email :hvhj
domain : hvhj


8. Function to find 'dog' in a string

In [14]:
def findDog(st):
    return 'dog' in st.split()

strg = findDog('Is there a dog here?')
print(strg)

True


9. lambda and filter() function to filter out words that dont start with the letter s

In [15]:
a = ['soup', 'dog', 'cat', 'salad', 'bat', 'sand', 'luke', 'emia']

alist = list(filter(lambda g: g.startswith('s'), a))

print(alist)


['soup', 'salad', 'sand']


10. you are driving too fast,and a police officer stop you. write a function to return one of 3 possible results: "no ticket", "small ticket" , "big ticket". If yout speed is 60 or less, the result will be "no ticket,if your speed is between 61 to 80 the result will be "small ticket" and if the speed is 81 or more the result will be "big ticket" unless if its your birthday(encoded as boolean value in the parameters of the function) on your birthday your speed can be 5 higher in all cases.

In [16]:
def ticket(speed):
    if speed <= 60:
        return "No ticket"
    elif 61 <= speed <= 80:
        return "Small ticket"
    else:
        return "Big ticket"

speed= input("Enter your speed: ")
birthday= input("Is it your birthday? (yes/no): ")

speed = int(speed)
result = ticket(speed)

if birthday=="no": 
  print(result)
else:
  print("no ticket")


Enter your speed: 8
Is it your birthday? (yes/no): yes
no ticket


1. Write a OOP in python to input empid, name, basic salary, no. of experience in yrs.
Calculate hra(35% of basic), da (58% of basic) and pf (9.5% of basic).
Also calculate bonus based on experience in years.
If experience in years is >= 30, bonus must be 59% of basic,
If experience in years is >=23, bonus must be 51% of basic,
If experience in years is >=15, bonus must be 45% of basic,
If experience in years is >=7, bonus must be 33% of basic,
If experience in years is <7, bonus must be 16% of basic
Calculate netsalary as basic+da+hra-pf+bonus.
Create a class, constructor to create instance variables, getter-setter for each variable,
calculative functions for operative variables. A class methods/function should not contain

In [17]:
class employee:     
    def __init__(self) :
        self.userName = input("Enter Your Name")
        self.salary = int(input("Enter Your Basic Salary"))
        self.experience = input("Enter Your Experience Year")
        self.hra = 0
        self.da = 0
        self.pf = 0
        self.bonus = 0

    def calculate(self):
        self.hra = 0.35 * self.salary
        self.da = 0.58 * self.salary
        self.pf = 0.095 * self.salary
        print("hra is " ,self.hra , "da is", self.da , "pf is" ,self.pf )

    def bonusSalary(self):

        if self.experience >= 30:
             self.bonus = .59 * self.salary 
        elif self.experience >= 23:
             self.bonus = .51 * self.salary 
        elif self.experience >= 15:
             self.bonus = .45 * self.salary     
        elif self.experience >= 7:
             self.bonus = .33 * self.salary   
        elif self.experience < 7:
             self.bonus = .16 * self.salary 

    def netSalary(self):
        self.calculate()
        self.bonusSalary
        self.net = self.bonus + self.salary + self.hra +  self.da + self.pf 
        print("Net salary is" , self.net)



husain=employee()
husain.netSalary()

Enter Your NameHusain
Enter Your Basic Salary10000000
Enter Your Experience Year10
hra is  3500000.0 da is 5800000.0 pf is 950000.0
Net salary is 20250000.0


In [18]:

n = int(input("Enter length of list")) 
lst1 = []
newList = []

def lstCalc() :
    for i in range(0,n):
        user = int(input("enter your no."))
        lst1.append(user)
    print(lst1)

def lst1Calc():
    lstCalc()
    for y in range (0 , n//2):
        k = lst1[y]+lst1[n-1-y]
        newList.append(k)
    sset = set(newList)
    tupp = tuple(sset)
    print(tupp)
            
lst1Calc()   
            

Enter length of list5
enter your no.1
enter your no.2
enter your no.3
enter your no.4
enter your no.4
[1, 2, 3, 4, 4]
(5, 6)


In [19]:

class lstEmp():

    n = int(input("Enter length of list")) 
    lst1 = []
    newList = []

    def lstCalc() :
        for i in range(0,n):
            user = int(input("enter your no."))
            lst1.append(user)
        print(lst1)

    def lst1Calc():
        lstCalc()
        for y in range (0 , n//2):
            k = lst1[y]+lst1[n-1-y]
            newList.append(k)
        sset = set(newList)
        tupp = tuple(sset)
        print(tupp)
lisst = lstEmp()
lisst.lst1Calc()   
            

Enter length of list2


TypeError: lstEmp.lst1Calc() takes 0 positional arguments but 1 was given

Write an OOP program to perform addition, base and power, concatenation, max, min of two
numbers stored in two different objects created from same class.
n1=MyNumber(2)
n2=MyNumber()
n2.setNum(5)
n3=n1.add(n2)
print("Addition is ",n3.getNum()) #7
n3=n1.raisedTo(n2)
print(n1.getNum()," raised to ",n2.getNum()," is ",n3.getNum()) #32
n3=n1.concat(n2)
print("Concat answer is ",n3.getNum()) #25
n3=n1.max(n2)
print("Max is ",n3.getNum())

In [20]:
class Numbers:
    def __init__(self , num = 0):
        self.num = num 
    def setNum(self,num):
        self.num = num 
    def getNum(self):
        return self.num 
    def add(self, n2 ):
        n3 =Numbers(self.num + n2.num)
        return n3
    def power(self , n2):
        n3 =Numbers(self.num**n2.num)
        return n3
    def concat(self , n2):
        n3 =Numbers(str(self.num)+str(n2.num))
        return n3
    def min1(self,n2):
        n3 =Numbers(min(self.num , n2.num))
        return n3
    def max1(self,n2):
        n3 =Numbers(max(self.num , n2.num))
        return n3
        


n1 = Numbers()
n1.setNum(5)
##print(n1.getNum())
n2 = Numbers()
n2.setNum(2)
n3 = n1.add(n2)
print("Addition is ",n3.getNum())
n3 = n1.power(n2)
print("Power is ",n3.getNum())
n3 = n1.concat(n2)
print("Concatenation is ",n3.getNum())
n3 = n1.min1(n2)
print("Min  is ",n3.getNum())
n3 = n1.max1(n2)
print("Max is ",n3.getNum())

Addition is  7
Power is  25
Concatenation is  52
Min  is  2
Max is  5


In [ ]:
Mydict = {"Enrollment Id": [12345, 45667, 16789, 69433],
        "Student Name": ["Diksha", "Jiva", "Ronit", "Heena"],
        "Email Id": ["Diksha@nuv.ac.in", "Jiva@nuv.ac.in", "Ronit@nuv.ac.in", "Heena@nuv.ac.in"]}

value = int(input("Enter id: "))
for i in range(len(Mydict["Enrollment Id"])):
    if Mydict["Enrollment Id"][i] == value:
        print("Enrollment Id:", Mydict["Enrollment Id"][i])
        print("Student Name:", Mydict["Student Name"][i])
        print("Email Id:", Mydict["Email Id"][i])

value = input("Enter name: ")
for j in range(len(Mydict["Student Name"])):
    if Mydict["Student Name"][j] == value:
        print("Enrollment Id:", Mydict["Enrollment Id"][j])
        print("Student Name:", Mydict["Student Name"][j])
        print("Email Id:", Mydict["Email Id"][j])

value = input("Enter email: ")
for k in range(len(Mydict["Email Id"])):
    if Mydict["Email Id"][k] == value:
        print("Enrollment Id:", Mydict["Enrollment Id"][k])
        print("Student Name:", Mydict["Student Name"][k])
        print("Email Id:", Mydict["Email Id"][k])



Enter id: 222211


In [ ]:
data = [
    (12345, "Diksha", "Diksha@nuv.ac.in"),
    (45667, "Jiva", "Jiva@nuv.ac.in"),
    (16789, "Ronit", "Ronit@nuv.ac.in"),
    (69433, "Heena", "Heena@nuv.ac.in")
]
def searchById(sid):
    for i in data:
        if i[0] == sid:
            print(i)

def searchByName(sname):
    for j in data:
        if j[1] == sname:
            print(j)

def searchByEmail(semail):
    for z in data:
        if z[2] == semail:
            print(z)

sid = int(input("Enter id: "))
sname = input("Enter name: ")
semail = input("Enter email: ")

searchById(sid)
searchByName(sname)
searchByEmail(semail)

In [ ]:
Mydict = {"Enrollment Id": [12345, 45667, 16789, 69433],
        "Student Name": ["Diksha", "Jiva", "Ronit", "Heena"],
        "Email Id": ["Diksha@nuv.ac.in", "Jiva@nuv.ac.in", "Ronit@nuv.ac.in", "Heena@nuv.ac.in"]}



In [ ]:
Data = [
    (12345, "Diksha" , "Diksha@nuv.ac.in" ),
    (45667,"Jiva", "Jiva@nuv.ac.in"),
    (16789,"Ronit","Ronit@nuv.ac.in" ),
    (69433,"Heena" , "Heena@nuv.ac.in")
]

mydict = {"Enroll" :[] , "Student Name" : [] , "Email" :[]}

for d in Data :
    mydict["Enroll"].append(d[0])
    mydict["Student Name"].append(d[1])
    mydict["Email"].append(d[2])

mydict

In [ ]:
mydict["Enroll"]=[d[0] for d in Data]
mydict["Student Name"]=[d[1] for d in Data]
mydict["Email"]=[d[2] for d in Data]
mydict



In [ ]:
Personal = {"Name" : ["Husain Ali"] , "Id" :[22000234] , "College" : ["Navrachna University"] }
import json 
file = open("Filedata.json" , "w")
jsondata = json.dumps(Personal)
file.write(jsondata)

In [ ]:
filer = open("Filedata.json" , "r")
dataread= json.load(filer)

dataread


In [ ]:
import csv 

with open("12001.csv", "r") as filecr:
    filecrd = csv.reader(filecr)
    for row in filecrd:
        print(row)

filecrd


Unit - 2

In [ ]:
#Numpy 

In [1]:
import numpy as np

In [2]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.ones(10) *5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [6]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [7]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.random.rand(1)

array([0.4438903])

In [10]:
np.random.rand(25)

array([0.99039379, 0.21147782, 0.37452828, 0.36864606, 0.49594349,
       0.01896381, 0.10008566, 0.19695419, 0.65297708, 0.35028445,
       0.03489679, 0.4971192 , 0.00899112, 0.47633518, 0.95906948,
       0.53472134, 0.76671211, 0.14917697, 0.30951816, 0.64364599,
       0.85456885, 0.64913043, 0.23170476, 0.70566314, 0.63008941])

In [2]:
import numpy as np 
np.linspace(0.01 , 1 , 100)


array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [12]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [13]:
import numpy as np 
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [14]:
mat = np.arange(1,26)
mat = mat.reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [15]:
mat[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [16]:
mat[3,4]

20

In [17]:
mat[0:3 , 1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [18]:
mat[4:5]

array([[21, 22, 23, 24, 25]])

In [19]:
mat[3:5 , 0:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [20]:
np.sum(mat)

325

In [21]:
np.std(mat)

7.211102550927978

In [22]:
np.sum(mat,axis = 1)

array([ 15,  40,  65,  90, 115])

In [23]:
oned = np.arange(0,12)
oned

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
twod = np.arange(0,12).reshape(3,4)
twod

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
threed = np.arange(0,12).reshape(3,2,2)
threed

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [26]:
threed = np.arange(0,12).reshape(3,2,2)
threed

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [27]:
threed = np.arange(0,12).reshape(3,2,2)
threed

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [28]:
three = threed.dtype
one = oned.dtype
two = twod.dtype
print(three,one,two)

int64 int64 int64


In [29]:
ones = oned.shape
twos = twod.shape
threes = threed.shape
print(ones , twos , threes )

(12,) (3, 4) (3, 2, 2)


In [30]:
ones = oned.ndim
twos = twod.ndim
threes = threed.ndim
print(ones , twos , threes )

1 2 3


In [31]:
np.empty((3))

array([1., 1., 1.])

In [32]:
np.zeros(12)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.ones(12).reshape(4,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
Marks = np.random.randint(0,100,20)
Marks

array([39, 10, 59, 22, 40, 38, 48, 57, 62, 29, 19, 99,  4, 22, 87, 98, 95,
       18, 81, 53])

In [35]:
ascend = np.sort(Marks)
ascend

array([ 4, 10, 18, 19, 22, 22, 29, 38, 39, 40, 48, 53, 57, 59, 62, 81, 87,
       95, 98, 99])

In [36]:
reverse = ascend[::-1]
reverse

array([99, 98, 95, 87, 81, 62, 59, 57, 53, 48, 40, 39, 38, 29, 22, 22, 19,
       18, 10,  4])

In [37]:
np.flip(ascend)

array([99, 98, 95, 87, 81, 62, 59, 57, 53, 48, 40, 39, 38, 29, 22, 22, 19,
       18, 10,  4])

In [38]:
Deep = reverse.copy()
Deep

array([99, 98, 95, 87, 81, 62, 59, 57, 53, 48, 40, 39, 38, 29, 22, 22, 19,
       18, 10,  4])

In [39]:
iden = np.eye(5)
iden

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
iden.reshape(25)

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [41]:
threel = np.arange(0,9).reshape(3,3)
threel

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
import numpy as np



In [45]:
np.hstack((threel,[[11],[13],[14]]))

array([[ 0,  1,  2, 11],
       [ 3,  4,  5, 13],
       [ 6,  7,  8, 14]])

In [48]:
np.hsplit(threel,3)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [54]:
np.vsplit(threel,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [57]:
np.eye(3)+4

array([[5., 4., 4.],
       [4., 5., 4.],
       [4., 4., 5.]])

In [70]:
floats = np.random.uniform(10,60,10)
floats

array([53.05701378, 19.87327099, 10.98039014, 27.75140511, 22.17091577,
       52.75469536, 23.26828764, 40.70098567, 47.15094023, 58.06707638])

In [69]:
np.floor(floats)


array([43., 19., 54., 49., 28., 38., 59., 21., 46., 50.])

In [73]:
np.ceil(floats)


array([54., 20., 11., 28., 23., 53., 24., 41., 48., 59.])

In [78]:
np.round(floats,decimals=2)


array([53.06, 19.87, 10.98, 27.75, 22.17, 52.75, 23.27, 40.7 , 47.15,
       58.07])

In [84]:
five5 = np.arange(1,26).reshape(5,5)
five5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [86]:
five5.min(axis=0)

array([1, 2, 3, 4, 5])

In [87]:
five5.max(axis=0)

array([21, 22, 23, 24, 25])

In [91]:
np.var(five5 , axis=0)

array([50., 50., 50., 50., 50.])

In [92]:
np.std(five5,axis=0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [101]:
FullFill = np.full((10),'NaN')
FullFill

array(['NaN', 'NaN', 'NaN', 'NaN', 'NaN', 'NaN', 'NaN', 'NaN', 'NaN',
       'NaN'], dtype='<U3')

In [104]:
FullFill[6] =200
FullFill

array(['NaN', 'NaN', 'NaN', 'NaN', 'NaN', 'NaN', '200', 'NaN', 'NaN',
       'NaN'], dtype='<U3')

In [2]:
import numpy as np
np.nonzero([1,0,2,0,0,4,0,8])

(array([0, 2, 5, 7]),)

In [24]:
one = np.ones((10,10))
one[1:9 , 1:9] = 0
one

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [25]:
point = np.ones((5,5))*1.5 
point[1:4 , 1:4]=0.5
point

array([[1.5, 1.5, 1.5, 1.5, 1.5],
       [1.5, 0.5, 0.5, 0.5, 1.5],
       [1.5, 0.5, 0.5, 0.5, 1.5],
       [1.5, 0.5, 0.5, 0.5, 1.5],
       [1.5, 1.5, 1.5, 1.5, 1.5]])

In [48]:
check = np.ones((8,8))
check[::2,::2] = 0
check[1::2 , 1::2] = 0
check

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [56]:
mat1 = np.random.randint((3,3))
mat2= np.random.randint((3,3))

add = mat1+mat2
Substract = mat1 - mat2
multiply = mat1@mat2


print(add , Substract , multiply)

[3 0] [1 0] 2


In [10]:
np.random.uniform(1,20,16).reshape(4,4)

array([[ 2.90519818, 17.71811684,  3.02230432, 18.34297135],
       [15.46939429,  2.36340745,  3.21956576, 14.50921793],
       [14.41214893,  2.5700953 , 17.69273637,  5.37145255],
       [12.20807034, 14.87900231,  8.08946613, 11.58148612]])

In [11]:
np.arange(0,26)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
np.linspace(0,36,36)

array([ 0.        ,  1.02857143,  2.05714286,  3.08571429,  4.11428571,
        5.14285714,  6.17142857,  7.2       ,  8.22857143,  9.25714286,
       10.28571429, 11.31428571, 12.34285714, 13.37142857, 14.4       ,
       15.42857143, 16.45714286, 17.48571429, 18.51428571, 19.54285714,
       20.57142857, 21.6       , 22.62857143, 23.65714286, 24.68571429,
       25.71428571, 26.74285714, 27.77142857, 28.8       , 29.82857143,
       30.85714286, 31.88571429, 32.91428571, 33.94285714, 34.97142857,
       36.        ])

In [42]:
mama = np.random.randint(0,25,)
mama


array([21, 11, 13,  2, 14, 22, 21, 12,  7])

In [33]:
jja = np.arange(1,26).reshape(5,5)
jja

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [35]:
jja[3:5 , 2:5 ]

array([[18, 19, 20],
       [23, 24, 25]])

In [39]:
np.sum?

In [51]:
py = np.ones((10,10))*3.14
py[1:9 , 1:9] = 0
py

array([[3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 3.14],
       [3.14, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 3.14],
       [3.14, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 3.14],
       [3.14, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 3.14],
       [3.14, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 3.14],
       [3.14, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 3.14],
       [3.14, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 3.14],
       [3.14, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14]])

In [52]:
np.sum(py , axis = 0)

array([31.4 ,  6.28,  6.28,  6.28,  6.28,  6.28,  6.28,  6.28,  6.28,
       31.4 ])

In [60]:
py = np.vstack((py,[4,4,4,4,4,4,4,4,4,4]))
py

array([[3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 3.14],
       [3.14, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 3.14],
       [3.14, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 3.14],
       [3.14, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 3.14],
       [3.14, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 3.14],
       [3.14, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 3.14],
       [3.14, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 3.14],
       [3.14, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ]])

In [63]:
np.hsplit(py,10)

[array([[3.14],
        [3.14],
        [3.14],
        [3.14],
        [3.14],
        [3.14],
        [3.14],
        [3.14],
        [3.14],
        [3.14],
        [4.  ]]),
 array([[3.14],
        [0.  ],
        [0.  ],
        [0.  ],
        [0.  ],
        [0.  ],
        [0.  ],
        [0.  ],
        [0.  ],
        [3.14],
        [4.  ]]),
 array([[3.14],
        [0.  ],
        [0.  ],
        [0.  ],
        [0.  ],
        [0.  ],
        [0.  ],
        [0.  ],
        [0.  ],
        [3.14],
        [4.  ]]),
 array([[3.14],
        [0.  ],
        [0.  ],
        [0.  ],
        [0.  ],
        [0.  ],
        [0.  ],
        [0.  ],
        [0.  ],
        [3.14],
        [4.  ]]),
 array([[3.14],
        [0.  ],
        [0.  ],
        [0.  ],
        [0.  ],
        [0.  ],
        [0.  ],
        [0.  ],
        [0.  ],
        [3.14],
        [4.  ]]),
 array([[3.14],
        [0.  ],
        [0.  ],
        [0.  ],
        [0.  ],
        [0.  ],
        [0.  ]

In [2]:
import numpy as np 
import pandas as pd 

In [4]:
a = [95,65,75]

servar = pd.Series(a, index = ["Python", "DSA", "DBMS"])

print(servar)

Python    95
DSA       65
DBMS      75
dtype: int64
